name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add es6
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: github.repository == 'terminusdb/terminusdb-documents-ui' && github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main-es6
        force: true
